name: Decir hola

on: 
  push:
    branches:
      - main

jobs: 
  hello_world:
    runs-on: ubuntu-18.04
    steps: 
      - name: echo the message
        run: |
          echo "Hola Juan"
      - name: Dime una fecha
        run: date
      - run: ls -l