name: Pipeline para despliegues

on: 
  push:
    branches:
      - main

jobs: 
  #Nombre del trabajo
  despliegue:
    #Máquina en la que corre el trabajo
    runs-on: ubuntu-18.04
    #Pasos a ejecutar de este trabajo
    steps:
    #Uso de la acción checkout para comprobar el estado del repositorio
    - uses: actions/checkout@v2
      with: 
      #Solo se hace check a la versión anterior
        fetch-depth: 0
      #Uso de la acción de Github para instalar node (ver en marketplace de Github)
    - uses: actions/setup-node@v3
      with:
        node-version: 14
      #Comandos para nodejs
    - name: Instalación de dependencias
      run: npm install --no-audit --no-fund --no-optional
    - name: Linter
      run: npm run eslint
    - name: Construcción del proyecto
      run: npm run build
    - name: Testeo 
      run: npm test