name: Pipeline para despliegues

on: 
  push:
    branches:
      - main

jobs: 
  despliegue:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Instalación de dependencias
      run: npm install
    - name: Linter
      run: npm run eslint