name: Pipeline para despliegues

on: 
  push:
    branches:
      - main

jobs: 
  #Nombre del trabajo
  despliegue:
    #Máquina en la que corre el trabajo
    runs-on: ubuntu-18.04
    #Pasos a ejecutar de este trabajo
    steps:
    #Uso de la acción checkout para comprobar el estado del repositorio
    - uses: actions/checkout@v2
      with: 
      #Solo se hace check a la versión anterior
        fetch-depth: 0
      #Uso de la acción de Github para instalar node (ver en marketplace de Github)
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      #Comandos para nodejs
    - name: Instalación de dependencias
      run: npm ci
    - name: Linter
      run: npm run eslint
    - name: Construcción del proyecto
      run: npm run build
    - name: Testeo 
      run: npm test
    - name: Testeo Entorno a Entrono (E2E)
      uses: cypress-io/github-action@v2
      with: 
        command: npm run test:e2e
        start: npm run start-test
        wait-on: http://localhost:5000